/**
 * MAIN test file for the Advent of code
 */

package org.aocday7;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AocTest {

    static final String EXAMPLE_INPUT = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

    @Test
    void problem1Solution() {
        var result = Solution.solveProblem1(EXAMPLE_INPUT);
        assertEquals(21, result);
    }
}
